//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.ContactInfo in the schema.
    /// </summary>
    public partial class ContactInfo
    {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for ContactInfo constructor in the schema.
        /// </summary>
        public ContactInfo()
        {
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public virtual string Contact
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for AltContact in the schema.
        /// </summary>
        public virtual string AltContact
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Gender in the schema.
        /// </summary>
        public virtual string Gender
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for MaritalStatus in the schema.
        /// </summary>
        public virtual string MaritalStatus
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string AltEmail
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for Dob in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Dob
        {
            get;
            set;
        }
    }
}
