//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;


namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.PaymentTransaction in the schema.
    /// </summary>
    public partial class PaymentTransaction {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PaymentTransaction constructor in the schema.
        /// </summary>
        public PaymentTransaction()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.AccountTransactions = new HashSet<AccountTransaction>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TxDate in the schema.
        /// </summary>
        public virtual System.DateTime TxDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Balance in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Balance
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Paid in the schema.
        /// </summary>
        public virtual decimal Paid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pending in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Pending
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        public virtual string Status
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PymtMode in the schema.
        /// </summary>
        public virtual string PymtMode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BankName in the schema.
        /// </summary>
        public virtual string BankName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ChequeNo in the schema.
        /// </summary>
        public virtual string ChequeNo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PymtModeTxDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> PymtModeTxDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AccountTransactions in the schema.
        /// </summary>
        public virtual ISet<AccountTransaction> AccountTransactions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PaymentMaster in the schema.
        /// </summary>
        public virtual PaymentMaster PaymentMaster
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CancelledPaymentTransaction in the schema.
        /// </summary>
        public virtual PaymentTransaction CancelledPaymentTransaction
        {
            get;
            set;
        }
    }

}
