//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.CoCustomer in the schema.
    /// </summary>
    public partial class CoCustomer {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CoCustomer constructor in the schema.
        /// </summary>
        public CoCustomer()
        {
            this.IsPoa = @"N";
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MiddleName in the schema.
        /// </summary>
        public virtual string MiddleName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Gender in the schema.
        /// </summary>
        public virtual string Gender
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Dob in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> Dob
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pan in the schema.
        /// </summary>
        public virtual string Pan
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsPoa in the schema.
        /// </summary>
        public virtual string IsPoa
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        public virtual Customer Customer
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_SALUTATION_ID in the schema.
        /// </summary>
        public virtual MasterControlData SalutationId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_RELATION_WH_PRIM_CUST in the schema.
        /// </summary>
        public virtual MasterControlData RelationWhPrimCust
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_OCCUPATION in the schema.
        /// </summary>
        public virtual MasterControlData Occupation
        {
            get;
            set;
        }
    }

}
