//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.Customer in the schema.
    /// </summary>
    public partial class Customer {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Customer constructor in the schema.
        /// </summary>
        public Customer()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.CoCustomers = new HashSet<CoCustomer>();
            this.PrUnitSaleDetails = new HashSet<PrUnitSaleDetail>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MiddleName in the schema.
        /// </summary>
        public virtual string MiddleName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pan in the schema.
        /// </summary>
        public virtual string Pan
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CoCustomers in the schema.
        /// </summary>
        public virtual ISet<CoCustomer> CoCustomers
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactInfo_CONTACT_INFO_ID in the schema.
        /// </summary>
        public virtual ContactInfo ContactInfo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_SALUTATION_ID in the schema.
        /// </summary>
        public virtual MasterControlData Salutation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_OCCUPATION in the schema.
        /// </summary>
        public virtual MasterControlData Occupation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrUnitSaleDetails in the schema.
        /// </summary>
        public virtual ISet<PrUnitSaleDetail> PrUnitSaleDetails
        {
            get;
            set;
        }
    }

}
