//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.PurchaseMaster in the schema.
    /// </summary>
    public partial class PurchaseMaster {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PurchaseMaster constructor in the schema.
        /// </summary>
        public PurchaseMaster()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchaseDate in the schema.
        /// </summary>
        public virtual System.DateTime PurchaseDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InvoiceNo in the schema.
        /// </summary>
        public virtual string InvoiceNo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PymtAmt in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> PymtAmt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tax in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Tax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Discount in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Discount
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TotalAmt in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> TotalAmt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmAccount in the schema.
        /// </summary>
        public virtual FirmAccount FirmAccount
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmMember in the schema.
        /// </summary>
        public virtual FirmMember FirmMember
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Property in the schema.
        /// </summary>
        public virtual Property Property
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchaseDetails in the schema.
        /// </summary>
        public virtual ISet<PurchaseDetail> PurchaseDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        public virtual Supplier Supplier
        {
            get;
            set;
        }
    }

}
