//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 9/3/2016 2:47:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.UserRole in the schema.
    /// </summary>
    public partial class UserRole {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for UserRole constructor in the schema.
        /// </summary>
        public UserRole()
        {
            this.UserDefinitions = new HashSet<UserDefinition>();
            this.UserEntitlements = new HashSet<UserEntitlement>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserDefinitions in the schema.
        /// </summary>
        public virtual ISet<UserDefinition> UserDefinitions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserEntitlements in the schema.
        /// </summary>
        public virtual ISet<UserEntitlement> UserEntitlements
        {
            get;
            set;
        }
    }

}
