//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoftNH
{

    /// <summary>
    /// There are no comments for ConstroSoftNH.State, ConstroSoftNH in the schema.
    /// </summary>
    public partial class State {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for State constructor in the schema.
        /// </summary>
        public State()
        {
            this.Addresses = new HashSet<Address>();
            this.Cities = new HashSet<City>();
            this.FirmAccounts = new HashSet<FirmAccount>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Abbreviation in the schema.
        /// </summary>
        public virtual string Abbreviation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public virtual ISet<Address> Addresses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        public virtual ISet<City> Cities
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        public virtual Country Country
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmAccounts in the schema.
        /// </summary>
        public virtual ISet<FirmAccount> FirmAccounts
        {
            get;
            set;
        }
    }

}
