//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoftNH
{

    /// <summary>
    /// There are no comments for ConstroSoftNH.Country, ConstroSoftNH in the schema.
    /// </summary>
    public partial class Country {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Country constructor in the schema.
        /// </summary>
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.FirmAccounts = new HashSet<FirmAccount>();
            this.States = new HashSet<State>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Abbreviation in the schema.
        /// </summary>
        public virtual string Abbreviation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public virtual ISet<Address> Addresses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmAccounts in the schema.
        /// </summary>
        public virtual ISet<FirmAccount> FirmAccounts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for States in the schema.
        /// </summary>
        public virtual ISet<State> States
        {
            get;
            set;
        }
    }

}
