//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoftNH
{

    /// <summary>
    /// There are no comments for ConstroSoftNH.Address, ConstroSoftNH in the schema.
    /// </summary>
    public partial class Address {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Address constructor in the schema.
        /// </summary>
        public Address()
        {
            this.EntityAddresses = new HashSet<EntityAddress>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PreferredAddress in the schema.
        /// </summary>
        public virtual string PreferredAddress
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AddressLine1 in the schema.
        /// </summary>
        public virtual string AddressLine1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AddressLine2 in the schema.
        /// </summary>
        public virtual string AddressLine2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Town in the schema.
        /// </summary>
        public virtual string Town
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Pin in the schema.
        /// </summary>
        public virtual string Pin
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlDatum in the schema.
        /// </summary>
        public virtual MasterControlDatum MasterControlDatum
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        public virtual City City
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        public virtual State State
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        public virtual Country Country
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EntityAddresses in the schema.
        /// </summary>
        public virtual ISet<EntityAddress> EntityAddresses
        {
            get;
            set;
        }
    }

}
