//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoftNH
{

    /// <summary>
    /// There are no comments for ConstroSoftNH.FirmMember, ConstroSoftNH in the schema.
    /// </summary>
    public partial class FirmMember {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for FirmMember constructor in the schema.
        /// </summary>
        public FirmMember()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.ContractorPayments = new HashSet<ContractorPayment>();
            this.EnquiryDetails = new HashSet<EnquiryDetail>();
            this.EnquiryFollowups = new HashSet<EnquiryFollowup>();
            this.PrUnitSaleDetails = new HashSet<PrUnitSaleDetail>();
            this.PropertyExpenses = new HashSet<PropertyExpense>();
            this.PurchaseMasters = new HashSet<PurchaseMaster>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EmployeeId in the schema.
        /// </summary>
        public virtual string EmployeeId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MiddleName in the schema.
        /// </summary>
        public virtual string MiddleName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for JoiningDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> JoiningDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Qualification in the schema.
        /// </summary>
        public virtual string Qualification
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactInfo in the schema.
        /// </summary>
        public virtual ContactInfo ContactInfo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContractorPayments in the schema.
        /// </summary>
        public virtual ISet<ContractorPayment> ContractorPayments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        public virtual Department Department
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryFollowups in the schema.
        /// </summary>
        public virtual ISet<EnquiryFollowup> EnquiryFollowups
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlDatum_SALUTATION_ID in the schema.
        /// </summary>
        public virtual MasterControlDatum MasterControlDatum_SALUTATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlDatum_DESIGNATION_ID in the schema.
        /// </summary>
        public virtual MasterControlDatum MasterControlDatum_DESIGNATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrUnitSaleDetails in the schema.
        /// </summary>
        public virtual ISet<PrUnitSaleDetail> PrUnitSaleDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyExpenses in the schema.
        /// </summary>
        public virtual ISet<PropertyExpense> PropertyExpenses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchaseMasters in the schema.
        /// </summary>
        public virtual ISet<PurchaseMaster> PurchaseMasters
        {
            get;
            set;
        }
    }

}
