//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.EnquiryDetail, ConstroSoft in the schema.
    /// </summary>
    public partial class EnquiryDetail {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for EnquiryDetail constructor in the schema.
        /// </summary>
        public EnquiryDetail()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.EnquiryFollowups = new HashSet<EnquiryFollowup>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MiddleName in the schema.
        /// </summary>
        public virtual string MiddleName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> EnquiryDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Budget in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Budget
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        public virtual string Status
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FollowupDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FollowupDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CloseReason in the schema.
        /// </summary>
        public virtual string CloseReason
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactInfo in the schema.
        /// </summary>
        public virtual ContactInfo ContactInfo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_SALUTATION_ID in the schema.
        /// </summary>
        public virtual MasterControlData SalutationId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_OCCUPATION in the schema.
        /// </summary>
        public virtual MasterControlData Occupation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_PROPERTY_TYPE in the schema.
        /// </summary>
        public virtual MasterControlData PropertyType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_PROPERTY_LOCATION in the schema.
        /// </summary>
        public virtual MasterControlData PropertyLocation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Property in the schema.
        /// </summary>
        public virtual Property Property
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_PR_UNIT_TYPE in the schema.
        /// </summary>
        public virtual MasterControlData PrUnitType
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MasterControlData_ENQUIRY_SOURCE in the schema.
        /// </summary>
        public virtual MasterControlData EnquirySource
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmMember in the schema.
        /// </summary>
        public virtual FirmMember FirmMember
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryFollowups in the schema.
        /// </summary>
        public virtual ISet<EnquiryFollowup> EnquiryFollowups
        {
            get;
            set;
        }
    }

}
