//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.MasterControlData, ConstroSoft in the schema.
    /// </summary>
    public partial class MasterControlData {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for MasterControlData constructor in the schema.
        /// </summary>
        public MasterControlData()
        {
            this.SystemDefined = @"N";
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.Addresses = new HashSet<Address>();
            this.CoCustomers_SALUTATION_ID = new HashSet<CoCustomer>();
            this.CoCustomers_RELATION_WH_PRIM_CUST = new HashSet<CoCustomer>();
            this.CoCustomers_OCCUPATION = new HashSet<CoCustomer>();
            this.Contractors = new HashSet<Contractor>();
            this.Customers_SALUTATION_ID = new HashSet<Customer>();
            this.Customers_OCCUPATION = new HashSet<Customer>();
            this.Documents = new HashSet<Document>();
            this.EnquiryDetails_SALUTATION_ID = new HashSet<EnquiryDetail>();
            this.EnquiryDetails_OCCUPATION = new HashSet<EnquiryDetail>();
            this.EnquiryDetails_PROPERTY_TYPE = new HashSet<EnquiryDetail>();
            this.EnquiryDetails_PROPERTY_LOCATION = new HashSet<EnquiryDetail>();
            this.EnquiryDetails_PR_UNIT_TYPE = new HashSet<EnquiryDetail>();
            this.EnquiryDetails_ENQUIRY_SOURCE = new HashSet<EnquiryDetail>();
            this.EnquiryFollowups = new HashSet<EnquiryFollowup>();
            this.FirmAccounts = new HashSet<FirmAccount>();
            this.FirmMembers_SALUTATION_ID = new HashSet<FirmMember>();
            this.FirmMembers_DESIGNATION_ID = new HashSet<FirmMember>();
            this.PrUnitSalePymts = new HashSet<PrUnitSalePymt>();
            this.PrUnitSaleTaxDetails = new HashSet<PrUnitSaleTaxDetail>();
            this.Properties_TYPE_ID = new HashSet<Property>();
            this.Properties_LOCATION_ID = new HashSet<Property>();
            this.PropertyCharges = new HashSet<PropertyCharge>();
            this.PropertyExpenses = new HashSet<PropertyExpense>();
            this.PropertyParkings = new HashSet<PropertyParking>();
            this.PropertyTaxDetails = new HashSet<PropertyTaxDetail>();
            this.PropertyUnits_UNIT_TYPE_ID = new HashSet<PropertyUnit>();
            this.PropertyUnits_FACING = new HashSet<PropertyUnit>();
            this.PropertyUnits_DIRECTION = new HashSet<PropertyUnit>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.StockMasters = new HashSet<StockMaster>();
            this.Suppliers = new HashSet<Supplier>();
            this.UserDefinitions = new HashSet<UserDefinition>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        public virtual string Type
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SystemDefined in the schema.
        /// </summary>
        public virtual string SystemDefined
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        public virtual ISet<Address> Addresses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CoCustomers_SALUTATION_ID in the schema.
        /// </summary>
        public virtual ISet<CoCustomer> CoCustomers_SALUTATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CoCustomers_RELATION_WH_PRIM_CUST in the schema.
        /// </summary>
        public virtual ISet<CoCustomer> CoCustomers_RELATION_WH_PRIM_CUST
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CoCustomers_OCCUPATION in the schema.
        /// </summary>
        public virtual ISet<CoCustomer> CoCustomers_OCCUPATION
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Contractors in the schema.
        /// </summary>
        public virtual ISet<Contractor> Contractors
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customers_SALUTATION_ID in the schema.
        /// </summary>
        public virtual ISet<Customer> Customers_SALUTATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customers_OCCUPATION in the schema.
        /// </summary>
        public virtual ISet<Customer> Customers_OCCUPATION
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        public virtual ISet<Document> Documents
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_SALUTATION_ID in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_SALUTATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_OCCUPATION in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_OCCUPATION
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_PROPERTY_TYPE in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_PROPERTY_TYPE
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_PROPERTY_LOCATION in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_PROPERTY_LOCATION
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_PR_UNIT_TYPE in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_PR_UNIT_TYPE
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryDetails_ENQUIRY_SOURCE in the schema.
        /// </summary>
        public virtual ISet<EnquiryDetail> EnquiryDetails_ENQUIRY_SOURCE
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnquiryFollowups in the schema.
        /// </summary>
        public virtual ISet<EnquiryFollowup> EnquiryFollowups
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmAccounts in the schema.
        /// </summary>
        public virtual ISet<FirmAccount> FirmAccounts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmMembers_SALUTATION_ID in the schema.
        /// </summary>
        public virtual ISet<FirmMember> FirmMembers_SALUTATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmMembers_DESIGNATION_ID in the schema.
        /// </summary>
        public virtual ISet<FirmMember> FirmMembers_DESIGNATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrUnitSalePymts in the schema.
        /// </summary>
        public virtual ISet<PrUnitSalePymt> PrUnitSalePymts
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrUnitSaleTaxDetails in the schema.
        /// </summary>
        public virtual ISet<PrUnitSaleTaxDetail> PrUnitSaleTaxDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Properties_TYPE_ID in the schema.
        /// </summary>
        public virtual ISet<Property> Properties_TYPE_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Properties_LOCATION_ID in the schema.
        /// </summary>
        public virtual ISet<Property> Properties_LOCATION_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyCharges in the schema.
        /// </summary>
        public virtual ISet<PropertyCharge> PropertyCharges
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyExpenses in the schema.
        /// </summary>
        public virtual ISet<PropertyExpense> PropertyExpenses
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyParkings in the schema.
        /// </summary>
        public virtual ISet<PropertyParking> PropertyParkings
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyTaxDetails in the schema.
        /// </summary>
        public virtual ISet<PropertyTaxDetail> PropertyTaxDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyUnits_UNIT_TYPE_ID in the schema.
        /// </summary>
        public virtual ISet<PropertyUnit> PropertyUnits_UNIT_TYPE_ID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyUnits_FACING in the schema.
        /// </summary>
        public virtual ISet<PropertyUnit> PropertyUnits_FACING
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PropertyUnits_DIRECTION in the schema.
        /// </summary>
        public virtual ISet<PropertyUnit> PropertyUnits_DIRECTION
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PurchaseDetails in the schema.
        /// </summary>
        public virtual ISet<PurchaseDetail> PurchaseDetails
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for StockMasters in the schema.
        /// </summary>
        public virtual ISet<StockMaster> StockMasters
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public virtual ISet<Supplier> Suppliers
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserDefinitions in the schema.
        /// </summary>
        public virtual ISet<UserDefinition> UserDefinitions
        {
            get;
            set;
        }
    }

}
