//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/09/2016 9:37:15 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace ConstroSoft
{

    /// <summary>
    /// There are no comments for ConstroSoft.PaymentMaster, ConstroSoft in the schema.
    /// </summary>
    public partial class PaymentMaster {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for PaymentMaster constructor in the schema.
        /// </summary>
        public PaymentMaster()
        {
            this.InsertDate = DateTime.Now;
            this.UpdateDate = DateTime.Now;
            this.Version = 0;
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.PrPostDatedCheques = new HashSet<PrPostDatedCheque>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual long Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PymtSource in the schema.
        /// </summary>
        public virtual string PymtSource
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TotalAmt in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> TotalAmt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TotalPaid in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> TotalPaid
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TotalPending in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> TotalPending
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TotalPdcAmt in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> TotalPdcAmt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        public virtual string Status
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrgPymtId in the schema.
        /// </summary>
        public virtual System.Nullable<long> OrgPymtId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PymtFlow in the schema.
        /// </summary>
        public virtual string PymtFlow
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FirmNumber in the schema.
        /// </summary>
        public virtual string FirmNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertDate in the schema.
        /// </summary>
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateDate in the schema.
        /// </summary>
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        public virtual long Version
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for InsertUser in the schema.
        /// </summary>
        public virtual string InsertUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UpdateUser in the schema.
        /// </summary>
        public virtual string UpdateUser
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PaymentTransactions in the schema.
        /// </summary>
        public virtual ISet<PaymentTransaction> PaymentTransactions
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrPostDatedCheques in the schema.
        /// </summary>
        public virtual ISet<PrPostDatedCheque> PrPostDatedCheques
        {
            get;
            set;
        }
    }

}
